config/routes.rb
Site1::Application.routes.draw do
  
  resources :password_resets, only: [:new, :edit, :create, :update]
  resources :account_activations, only: [:new, :edit, :create] 
  resources :orders
  resources :cart_items
  resources :carts
  resources :products
  resources :users

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "vitrin/index"
  get "signup" => "users#new"
  get 'catalog' => "vitrin#index"

  root 'home#index'
  get 'about' => 'home#about'






  

end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessor :dummy_token, :activation_token, :reset_pswd_token

	has_many :products, dependent: :destroy

	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
	                format: { with: VALID_EMAIL_REGEX },
	                uniqueness: { case_sensitive: false }
	
	validates :password, presence: true, length: { minimum: 6 }
	has_secure_password

	def reset_dummy_token
		@dummy_token=SecureRandom.urlsafe_base64
		dummy_digest=BCrypt::Password.create(@dummy_token)
		self.update_attribute(:dummy, dummy_digest)
		return @dummy_token
	end

	def set_activation_digest
		@activation_token=SecureRandom.urlsafe_base64
		activation_digest=BCrypt::Password.create(@activation_token)
		self.update_attribute(:activation_digest, activation_digest)
	end

	def create_reset_digest
		@reset_pswd_token=SecureRandom.urlsafe_base64
		reset_password_digest=BCrypt::Password.create(@reset_pswd_token)
		self.update_attribute(:reset_digest, reset_password_digest)
		self.update_attribute(:reset_sent_at, Time.zone.now)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :bounce_not_logged_in_user, only: [:show, :edit, :update, :destroy]
  before_action :bounce_incorrect_user,     only: [:show, :edit, :update, :destroy]
  before_action :bounce_non_admin_user,     only: [:index]
  before_action :set_user,                  only: [:show, :edit, :update, :destroy]


  # GET /users
  # GET /users.json
  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params_for_create)

    respond_to do |format|
      if @user.save
        @user.set_activation_digest
        UserMailer.account_activation(@user).deliver
        format.html { redirect_to root_url, notice: "Please check your email for your account activation..." }
        format.json { render action: 'show', status: :created, location: root_url }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params_for_update)
        format.html { redirect_to @user}
        format.json { head :no_content }
        flash[:success]='User was successfully updated.' 
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy unless @user.admin?
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params_for_create
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :image_url)
    end

    def user_params_for_update
      if params[:user][:password].blank? and params[:user][:password_confirmation].blank?
        params.require(:user).permit(:name, :email, :image_url, :password, :password_confirmation)
      else
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :image_url)
      end
      
    end

    def bounce_incorrect_user
      @user = User.find_by(id: params[:id])
      if @user
        unless @user == current_user or current_user.admin?
          flash[:failure]="only correct user or admin can do that"
          redirect_to(root_url)
        end
      else
        flash[:failure]="no such user found"
        redirect_to(root_url)
      end
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name, placeholder: 'required', class: "field" %>
  </div>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email, placeholder: 'required for account activation', class: "field" %>
  </div>
  <div>
    <%= f.label :image_url, "Image URL" %><br>
    <%= f.text_field :image_url, placeholder: 'optional', class: "field" %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password, placeholder: 'required', class: "field" %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation, placeholder: 'required', class: "field" %>
  </div>
  <p></p>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show Info', @user %> 
<% if logged_in? and current_user.admin? %>
|
	<%= link_to 'Back', users_path %>
<% end %>

app/views/users/index.html.erb
<h1>Listing users</h1>


<%= link_to 'New User', signup_path %>

<%=  will_paginate @users, class: "pagin"%>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Email</th>
      <th># products</th>
      <th>USER ID</th>
      <th></th>
      <th></th>
      <th></th>
      <th>admin?</th>
      <th>activated?</th>
    </tr>
  </thead>

  <tbody>    
    <% @users.each do |user| %>
      <% if user.admin? %>
        <tr class="line-admin"> 
      <% else %>
        <tr class="<%= cycle('line-odd','line-even') %>">
      <% end %>
        <td class='img-cell'><%= image_tag(user.image_url, class: "list-image") %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.products.size %></td>
        <td><%= user.id %></td>
        <td><%= link_to 'Show', user, class: "list-link" %></td>
        <td><%= link_to 'Edit', edit_user_path(user), class: "list-link" %></td>
      <% if user.admin? %>
        <td> </td>
      <% else %>
        <td><%= link_to 'Destroy', user, class: "list-link", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
        <td><%= user.admin? %></td>
        <td><%= user.activated? %></td>
      </tr>
    <% end %>
    
  </tbody>
</table>

<%= will_paginate @users, class: "pagin"%>




app/views/users/new.html.erb
<% if logged_in? %>

	<p> You need to log out first to sign up a new user...  </p>

<% else %>

	<h1>New user</h1>
	<%= render 'form' %>
	<%#= link_to 'All users', users_path %>

<% end %>


app/views/users/show.html.erb

<h2> Account Information </h2>

<table>
  <tr>
    <td><%= image_tag(@user.image_url, class: 'show-image') %></td>
    <td>
      <p>
        <strong>Name:</strong>
        <%= @user.name %>
      </p>
      <p>
        <strong>Email:</strong>
        <%= @user.email %>
      </p>
      <p>
        <%= link_to 'Edit Account Info', edit_user_path(@user) %> 
        <% if logged_in? and current_user.admin? %>
        | <%= link_to 'Back', users_path %>
        <% end %>
      </p>
    </td>
  </tr>
</table>

<% if @user.products.count > 0 %>

  <h4> List of products posted </h4>
  <% products=@user.products.paginate(page: params[:page], per_page: 5) %>
  <%= will_paginate products, class: "pagin" %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
      </tr>
    </thead>

    <tbody>
      <% products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= number_to_currency(product.price) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%#= will_paginate products, class: "pagin" %>

<% else %>
  
    <p> No products posted by you currently... </p>

<% end %>


<%= link_to 'Add/Edit your products', products_path  %>
<% unless @user.admin? %>
	<p> ----------------------------------------------------------- </p>
	<p> !!! if you delete your account you will loose all your data and you will be logged out !!! </p>
	<%= button_to '! delete this user account !', user_path(@user), method: :delete, 
		data: { confirm: 
		'CAUTION!!! You will be logged out and all your data will be lost... Are you sure?' } %>
<% end %>