config/routes.rb
Site1::Application.routes.draw do
  
  resources :password_resets, only: [:new, :edit, :create, :update]
  resources :account_activations, only: [:new, :edit, :create] 
  resources :orders
  resources :cart_items
  resources :carts
  resources :products
  resources :users

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "vitrin/index"
  get "signup" => "users#new"
  get 'catalog' => "vitrin#index"

  root 'home#index'
  get 'about' => 'home#about'






  

end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base

  belongs_to :product
  belongs_to :cart
  belongs_to :order
  
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :set_cart, only: [:create]
  before_action :set_cart_item, only: [:show, :edit, :update, :destroy]

  # GET /cart_items
  # GET /cart_items.json
  def index
    if current_user and current_user.admin?
      @cart_items = CartItem.all.order(:cart_id)
    else
      @cart_items = current_cart.cart_items.all if current_cart
    end
  end

  # GET /cart_items/1
  # GET /cart_items/1.json
  def show
  end

  # GET /cart_items/new
  def new
    @cart_item = CartItem.new
  end

  # GET /cart_items/1/edit
  def edit
  end

  # POST /cart_items
  # POST /cart_items.json
  def create
    product = Product.find_by(id: params[:product_id])
    not_found_same=true
    @cart.cart_items.each do |item|
      if item.product == product
        item.quantity +=1
        @cart_item=item
        not_found_same=false
        break
      end
    end
    @cart_item = @cart.cart_items.create(product: product, quantity: 1) if not_found_same
    
    session[:return_to] = nil if session[:return_to]
    session[:return_to] ||= request.referer
    number_of_items = number_of_cart_items(current_cart) # from carts_helper
    flash[:success]="Cart item was successfully added to your cart. There are #{number_of_items} items in your card." 
    respond_to do |format|
      if @cart_item.save
        format.html { redirect_to session[:return_to]}
        format.json { render action: 'show', status: :created, location: @cart_item.cart }
      else
        format.html { render action: 'new' }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cart_items/1
  # PATCH/PUT /cart_items/1.json
  def update
    respond_to do |format|
      if @cart_item.update(cart_item_params)
        format.html { redirect_to @cart_item, notice: 'Cart item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cart_items/1
  # DELETE /cart_items/1.json
  def destroy
    @cart_item.destroy
    respond_to do |format|
      format.html { redirect_to cart_items_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart_item
      @cart_item = CartItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_item_params
      params.require(:cart_item).permit(:product_id, :cart_id, :quantity)
    end

end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<h1>Cart Items</h1>

<% if @cart_items %>
  
  <% if current_user and current_user.admin? %>
    <p>--- under construction for admin ---</p>
    <table>
      <thead>
        <tr>
          <th></th>
          <th>Product</th>
          <th>Quantity</th>
          <th>Price</th>
          <th>owner</th>
          <th>order</th>
          <th>cart</th>
        </tr>
      </thead>
      <tbody>
        <% @cart_items.each do |item| %>
          <tr>
            <td><%= image_tag item.product.image_url, class: "list-image" if item.product.image_url %></td>
            <td><%= item.product.name %> <%#= cart_item.id %> </td>
            <td>
              <%= item.quantity %>
            </td>
            <td><%= number_to_currency item.product.price %></td>
            <td> <%= item.product.user ? item.product.user.id : "????" %> </td>
            <td> <%= item.order ? item.order.id : "none" %> </td>
            <td> <%= item.cart ? item.cart.id : "none" %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <p>--- under construction for admin ---</p>


  <% else %>
    <%= button_to 'Check out', new_order_path, method: :get %>
    <table>
      <thead>
        <tr>
          <th></th>
          <th>Product</th>
          <th>Quantity</th>
          <th>Price</th>
          <!-- <th></th> -->
          <!-- <th></th> -->
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% total = 0 %>
        <% num_of_items = 0 %>
        <% @cart_items.each do |item| %>
          <% total += item.product.price * item.quantity  %>
          <% num_of_items += item.quantity  %>
          <tr>
            <td><%= image_tag item.product.image_url, class: "list-image" %></td>
            <td><%= item.product.name %> <%#= cart_item.id %> </td>
            <td>
              <%= item.quantity %>
            </td>
            <td><%= number_to_currency item.product.price %></td>
            <!-- <td><%#= link_to 'Show', cart_item %></td> --
            <!-- <td><%#= link_to 'Edit', edit_cart_item_path(cart_item) %></td> -->
            <td><%= link_to 'Delete', item, method: :delete %></td>
            <td>
              <% if item.product.user == current_user %>
              <br>
               "Are you sure to buy this item?"
               <br>
               "This is one of your own posts..."
               <% end %> 
            </td>
          </tr>
        <% end %>
        <tr>
          <td></td>
          <td> <strong>Total:</strong> </td>
          <td><%= num_of_items %> items </td>
          <td><%= number_to_currency total %></td>
        </tr>
      </tbody>
    </table>
    <br>
    <%= button_to 'Empty Cart', cart_path(session[:cart_id]), method: :delete, data: {confirm: "Are you sure?"} %>
    <br>
  <% end %>  
<% else %>
  <p> there are no items in your shopping cart...</p>
  <%= link_to "Shop for items", catalog_url %>
<% end %>

app/views/cart_items/xxx_form.html.erb
<%= form_for(@cart_item) do |f| %>
  <% if @cart_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart_item.errors.count, "error") %> prohibited this cart_item from being saved:</h2>

      <ul>
      <% @cart_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product %><br>
    <%= f.text_field :product %>
  </div>
  <div class="field">
    <%= f.label :cart %><br>
    <%= f.text_field :cart %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cart_items/xxxedit.html.erb
<h1>Editing cart_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart_item %> |
<%= link_to 'Back', cart_items_path %>

app/views/cart_items/xxxnew.html.erb
<h1>New cart_item</h1>

<%= render 'form' %>

<%= link_to 'Back', cart_items_path %>

app/views/cart_items/xxxshow.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @cart_item.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @cart_item.cart %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @cart_item.quantity %>
</p>

<%= link_to 'Edit', edit_cart_item_path(@cart_item) %> |
<%= link_to 'Back', cart_items_path %>