config/routes.rb
Site1::Application.routes.draw do
  
  resources :password_resets, only: [:new, :edit, :create, :update]
  resources :account_activations, only: [:new, :edit, :create] 
  resources :orders
  resources :cart_items
  resources :carts
  resources :products
  resources :users

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "vitrin/index"
  get "signup" => "users#new"
  get 'catalog' => "vitrin#index"

  root 'home#index'
  get 'about' => 'home#about'






  

end

app/models/product.rb
class Product < ActiveRecord::Base
	
  belongs_to :user
  has_many :cart_items
  before_destroy :ensure_not_referenced 

	validates :name, :price, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}

	private
		def ensure_not_referenced
			if cart_items.empty?
				true
			else
				errors.add(:base, "cart items present")
			end
  	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :bounce_not_logged_in_user, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :bounce_incorrect_user,     only: [:edit, :update, :destroy]
  before_action :set_product,               only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if current_user.admin?
      @products = Product.order(:user_id).paginate(page: params[:page], per_page: 15)
    else
      @products = current_user.products.paginate(page: params[:page], per_page: 5)
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = current_user.products.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.create(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product}
        format.json { render action: 'show', status: :created, location: @product }
        flash[:success]='Product was successfully created.' 
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product }
        format.json { head :no_content }
        flash[:success]='Product was successfully updated.'
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :user_id, :image_url, :body)
    end

    def bounce_incorrect_user
      @product = Product.find_by(id: params[:id])
      if @product
        @user = @product.user
        if @user
          unless @user == current_user or current_user.admin?
            flash[:failure]="only correct user or admin can do that"
            redirect_to(root_url)
          end
        else
          flash[:failure]="no such user found"
          redirect_to(root_url)  
        end
      else
        flash[:failure]="no such product found"
        redirect_to(root_url)
      end
    end

end

app/helpers/products_helper.rb
module ProductsHelper
	def associated_orders(product)
		list=[]
		product.cart_items.each { |item| list << item.order if item.order }
	end
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_url, "Image URL" %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :body, 'Description'%><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'My Products', products_path %>

app/views/products/index.html.erb

<%= link_to 'Add new product', new_product_path %>
<%#= link_to 'CATALOG', catalog_path %>


<% if @products.count > 0  %>
 
  <% if current_user.admin? %>
    <h2>Listing all products for admin "<%= current_user.name %>"</h2>
  <% else %>
    <h2>Products posted by "<%= current_user.name %>"</h2>
  <% end %>

  <%= will_paginate @products, class: "pagin" %>
    <table>
      <tbody>
        <% @products.each do |product| %>
          <tr class="<%= cycle('line-odd','line-even') %>">
            <td class="img-cell"><%= image_tag(product.image_url, class: "list-image") %></td>
            <td><%= product.name %></td>
            <td><%= number_to_currency(product.price) %></td>
            <td><%= associated_orders(product).count %> orders </td>
            <td><%= link_to 'Show', product, class: "list-link" %></td>
            <td><%= link_to 'Edit', edit_product_path(product), class: "list-link" %></td>
            <td><%= link_to 'Delete', product, class: "list-link", method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <%= will_paginate @products, class: "pagin" %>


<% else %>

  <p><%= current_user.name %> is not posting any products currently. </p>
  
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb

<%= image_tag(@product.image_url, class: "show-image") %>

<% if logged_in? and current_user == @product.user %>
  <h2> --- THIS PRODUCT IS ONE OF YOUR POSTS --- </h2>
<% end %>

<strong><%= @product.name %> (<%= number_to_currency(@product.price) %>) </strong> 


<p>
  <strong>Description:</strong>
  <%= @product.body %>
</p>

<%= button_to "Add to cart", cart_items_path(product_id: @product), class: 'button-cart' %>

<p>
<% if logged_in? and (current_user == @product.user or current_user.admin?) %>
  <%= link_to 'Edit', edit_product_path(@product) %> |
  <%= link_to 'My Products', products_path %>
<% end %>
</p>


<p>
  <strong>Owner/User ID:</strong>
  <%= @product.user.id %>
</p>

<p>
  <strong>Owner/User Name:</strong>
  <%= @product.user.name %>
</p>

<p>
  <strong>Owner/User Image:</strong>
  <%= image_tag(@product.user.image_url, class: 'user-image') %>
</p>

<p>
  <strong>Owner/User Contact:</strong>
  <%= link_to 'contact seller', '#' %>
</p>
