config/routes.rb
Site1::Application.routes.draw do
  
  resources :password_resets, only: [:new, :edit, :create, :update]
  resources :account_activations, only: [:new, :edit, :create] 
  resources :orders
  resources :cart_items
  resources :carts
  resources :products
  resources :users

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "vitrin/index"
  get "signup" => "users#new"
  get 'catalog' => "vitrin#index"

  root 'home#index'
  get 'about' => 'home#about'






  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>eBazaar/<%= controller.controller_name %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="container"> 
			<%= link_to "eBazaar", root_url, id:'logo' %>
			<%= link_to "Catalog", catalog_url, id:'catalog-logo' %>
			<%= link_to "Shopping Cart [#{number_of_cart_items(current_cart)}]", cart_items_url, id:'cart-logo' %>
			<nav>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "HOME", root_url %></li>
					<li><%= link_to "About", about_url %></li>
					<% if logged_in? %>
						<li><%= link_to "Account Info", user_path(current_user) %></li>
						<li><%= link_to "My Products", products_path %></li>
						<li><%= link_to "Log out",  logout_path, method: :delete %></li>
						<li><%= image_tag current_user.image_url, class: "user-image" if current_user %></li>
					<% else %>
						<li><%= link_to "Log in",  login_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
		<div class="container">
			<div>
				<%= form_tag catalog_path, method: :get, id: 'search-bar' do %>
					<%#= label_tag :search_text, 'Search Catalog:' %>
					<%= text_field_tag :search_text, params[:search_text], placeholder: "search for goods", id: "search-box" %>
					<%= submit_tag "Search" %>
				<% end %>
			
				<div id='info-bar'>
				<% if logged_in? %>
					<% if current_user.admin? %>
						<span class="admin-link"><%= link_to "Orders", orders_path %></span>
						<span class="admin-link"><%= link_to "Carts", carts_path %></span>
						<span class="admin-link"><%= link_to "Cart_Items", cart_items_url %></span>
						<span class="admin-link"><%= link_to "All Users", users_path %></span>
					<% end %>
					<%= current_user.name %>
				<% end %>
				</div>

			</div>
		</div>
		<div class="container">
			<div id='flash-bar'>
			<% flash.each do |name, message| %>
				<div class="<%= name %>"><%= message %></div>
			<% end %>
			</div>
		</div>
	</header>
	<!-- [cart: <%#=current_cart.id if current_cart %>, <%#= session[:cart_id] %>] 
	[user: <%#=current_user.id if current_user %>, <%#= session[:user_id] %>] -->
	<div class="container">
		
		<%= yield %>

	</div>

</body>

</html>